/**
 * Deterministic Safety Boundary (Non-Diagnostic Guardrail)
 * 
 * Strict Invariants:
 * 1. AI MUST NOT generate medical diagnoses.
 * 2. AI MUST NOT prescribe treatments, medications, or recommend dosage changes.
 * 3. Summaries must remain objective, descriptive, and patient-comprehensible:
 *    - Example allowed: "Hemoglobin level is below the reference range indicated on your lab report (11.2 g/dL vs ref 12.0 - 15.5 g/dL)."
 *    - Example forbidden: "Patient has iron-deficiency anemia; start ferrous sulfate 325 mg daily."
 * 4. Every generated view renders the explicit clinical disclaimer:
 *    "For clinical synthesis and informational organization only. Not a medical diagnosis or treatment plan."
 */

export const MANDATORY_CLINICAL_DISCLAIMER =
  "For clinical synthesis and informational organization only. Not a medical diagnosis or treatment plan.";

// Prohibited affirmative diagnostic declarations (direct diagnostic assertion by AI)
// Carefully distinguishes from disclaimers ("Not a medical diagnosis") and source citations ("documented diagnosis in EHR")
const PROHIBITED_DIAGNOSTIC_PATTERNS = [
  /\b(?:diagnose\s+patient\s+with|diagnosing\s+patient\s+with)\b/i,
  /\b(?:we\s+conclude\s+the\s+patient\s+has|confirming\s+new\s+diagnosis\s+of)\b/i,
  /\bpatient\s+(?:now\s+)?has\s+(?:acute\s+)?(?:iron[- ]deficiency\s+anemia|type\s+[12]\s+diabetes|hypertension|ckd|heart\s+failure|myocardial\s+infarction|pneumonia|copd|sepsis)\b(?!\s+(?:noted|recorded|documented|stated|per|in\s+source|in\s+intake))/i,
  /\bthis\s+(?:confirms|establishes)\s+(?:the\s+)?diagnosis\s+of\b/i,
];

// Prohibited prescriptive directives (treatment or dosage instructions by AI)
// Distinguishes from metadata ("prescribedDate", "prescribing physician", "active prescription")
const PROHIBITED_PRESCRIPTIVE_PATTERNS = [
  /\b(?:i\s+prescribe|prescribing\s+rx\s+for|must\s+prescribe)\b/i,
  /\bstart(?:ing)?\s+(?:the\s+)?patient\s+on\s+[A-Za-z0-9]+\s+\d+/i,
  /\badminister\s+\d+\s*(?:mg|mcg|g|units)\s+immediately\b/i,
  /\b(?:increase|decrease|titrate)\s+(?:the\s+)?(?:dose|dosage)\s+to\s+\d+/i,
  /\btake\s+\d+\s*(?:mg|mcg|g|units|tablets)\s+(?:daily|every|bid|tid|po)\b/i,
  /\bdiscontinue\s+medication\s+promptly\s+without\s+physician\b/i,
];

export interface SafetyAuditResult {
  passed: boolean;
  violationsFound: string[];
  sanitizedText: string;
  enforcedDisclaimer: string;
}

/**
 * Audits any clinical text generated by an LLM or synthesis module against
 * the non-diagnostic deterministic safety boundary.
 */
export function auditSafetyBoundary(text: string): SafetyAuditResult {
  if (!text) {
    return {
      passed: true,
      violationsFound: [],
      sanitizedText: '',
      enforcedDisclaimer: MANDATORY_CLINICAL_DISCLAIMER,
    };
  }

  // Strip out standard clinical disclaimers before scanning to prevent false-positive self-triggering
  const textWithoutDisclaimer = text
    .replace(new RegExp(MANDATORY_CLINICAL_DISCLAIMER.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi'), '')
    .replace(/not\s+(?:a\s+)?medical\s+diagnosis/gi, '')
    .replace(/does\s+not\s+diagnose/gi, '');

  const violations: string[] = [];
  let sanitized = text;

  // 1. Audit against diagnostic patterns
  for (const pattern of PROHIBITED_DIAGNOSTIC_PATTERNS) {
    const match = textWithoutDisclaimer.match(pattern);
    if (match) {
      violations.push(`Diagnostic Declaration Detected: "${match[0]}"`);
    }
  }

  // 2. Audit against prescriptive patterns
  for (const pattern of PROHIBITED_PRESCRIPTIVE_PATTERNS) {
    const match = textWithoutDisclaimer.match(pattern);
    if (match) {
      violations.push(`Prescriptive Directive Detected: "${match[0]}"`);
    }
  }

  // 3. Deterministic remediation if violations were triggered
  if (violations.length > 0) {
    sanitized = sanitizeToObjectiveDescription(sanitized);
  }

  return {
    passed: violations.length === 0,
    violationsFound: violations,
    sanitizedText: sanitized,
    enforcedDisclaimer: MANDATORY_CLINICAL_DISCLAIMER,
  };
}

/**
 * Deterministically neutralizes prescriptive or diagnostic phrases
 * into safe, objective, descriptive clinical observations.
 */
export function sanitizeToObjectiveDescription(text: string): string {
  let clean = text;

  clean = clean.replace(
    /\bpatient (?:has|suffers from)\s+(anemia|type [12] diabetes|ckd|hypertension)\b/gi,
    "laboratory/clinical documents record parameters associated with $1"
  );
  clean = clean.replace(
    /\bconfirm(?:s|ing)? diagnosis of\b/gi,
    "consistent with documentation indicating"
  );
  clean = clean.replace(
    /\bdiagnosed with\b/gi,
    "documented in source record as"
  );

  clean = clean.replace(
    /\bprescribe\s+([A-Za-z0-9\s]+)/gi,
    "clinical documentation lists $1 (consult attending physician for review)"
  );
  clean = clean.replace(
    /\bstart patient on\s+([A-Za-z0-9\s]+)/gi,
    "clinical record references possible initiation of $1 (requires physician confirmation)"
  );
  clean = clean.replace(
    /\b(?:increase|decrease|titrate)\s+(?:the\s+)?(?:dose|dosage)\s*(?:to\s*)?([^\n.;]*)/gi,
    "laboratory changes may prompt physician evaluation of dosage ($1)"
  );

  return clean;
}

/**
 * Constructs an approved, objective, descriptive summary item for a lab result.
 * Strictly avoids diagnostic conclusions while highlighting document-stated limits.
 */
export function buildDescriptiveLabObservation(
  testName: string,
  value: string | number,
  unit: string | null,
  referenceRange: { low?: number; high?: number; text?: string } | null,
  status: 'LOW' | 'NORMAL' | 'HIGH' | 'ABNORMAL' | 'UNSPECIFIED'
): string {
  const formattedVal = `${value}${unit ? ' ' + unit : ''}`;

  if (!referenceRange || (!referenceRange.low && !referenceRange.high && !referenceRange.text)) {
    return `${testName} is recorded as ${formattedVal}. The source document did not specify a reference interval.`;
  }

  const rangeDesc = referenceRange.text
    ? referenceRange.text
    : referenceRange.low !== undefined && referenceRange.high !== undefined
    ? `${referenceRange.low} - ${referenceRange.high}`
    : referenceRange.high !== undefined
    ? `< ${referenceRange.high}`
    : `> ${referenceRange.low}`;

  if (status === 'HIGH') {
    return `${testName} level (${formattedVal}) is above the reference range indicated on your lab report (${rangeDesc}${unit ? ' ' + unit : ''}).`;
  }

  if (status === 'LOW') {
    return `${testName} level (${formattedVal}) is below the reference range indicated on your lab report (${rangeDesc}${unit ? ' ' + unit : ''}).`;
  }

  if (status === 'NORMAL') {
    return `${testName} level (${formattedVal}) is within the reference range indicated on your lab report (${rangeDesc}${unit ? ' ' + unit : ''}).`;
  }

  return `${testName} is recorded as ${formattedVal} (Reported range: ${rangeDesc}).`;
}
